# Generated by Django 5.1.3 on 2024-12-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
    ]
