# Generated by Django 5.1.3 on 2024-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joboffer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes internes sur le candidat'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20),
        ),
    ]
